server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "Prince12"

  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.2.0"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"

    sources:
      spotify: true
      applemusic: false
      deezer: false

    spotify:
      clientId: "e124e96cc9004a08a9a74f9bafcecd76"
      clientSecret: "8aa354d8e77c4fcfa64444264bdfd3c2"
      countryCode: "US"
